App restart required: Restart required
Application Starts with Main Window Hidden: Application Starts with Main Window Hidden
Auto-close window after action: Auto-close window after action
Boards, saved clips and menu items panel visible: Boards, saved clips and menu items panel visible
Both clipboard history and saved clips panels visible: Both clipboard history and saved clips panels visible
Change: Change
Click Set/Change button to start recording: Click Set/Change button to start recording
Clipboard history panel visible: Clipboard history panel visible
Configure how the system tray icon responds to mouse clicks: Configure how the system tray icon responds to mouse clicks
Configure the behavior of the Quick Paste window when selecting items: Configure the behavior of the Quick Paste window when selecting items
Configure which items to preserve when clearing clipboard history (both manual and auto-clear operations).: Configure which items to preserve when clearing clipboard history (both manual and auto-clear operations).
Control which panels are visible in the main window: Control which panels are visible in the main window
Copy items only (no auto-paste): Copy items only (no auto-paste)
Copy only from menu items: Copy only from menu items
Default Note Icon Type: Default Note Icon Type
Disable left-click context menu: Disable left-click context menu
Display navbar items only when the mouse hovers over the navigation bar to minimize visible UI elements: Display navbar items only when the mouse hovers over the navigation bar to minimize visible UI elements
Display persistent icons on clips that have notes to improve visual organization and make notes easier to discover.: Display persistent icons on clips that have notes to improve visual organization and make notes easier to discover.
Double-click toggles app visibility: Double-click toggles app visibility
Double-clicking the tray icon shows or hides the main application window: Double-clicking the tray icon shows or hides the main application window
Enable simplified, less boxy layout for a cleaner and more streamlined interface design: Enable simplified, less boxy layout for a cleaner and more streamlined interface design
Enable single-click to copy/paste clipboard history items and saved clips instead of requiring double-click.: Enable single-click to copy/paste clipboard history items and saved clips instead of requiring double-click.
Enabling either left-click option will disable the context menu to ensure proper functionality.: Enabling either left-click option will disable the context menu to ensure proper functionality.
Global System OS Hotkeys: Global System OS Hotkeys
Hide Collections Navbar: Hide Collections Navbar
Hide collections menu dropdown on the navigation bar: Hide collections menu dropdown on the navigation bar
Hide collections menu on the navbar: Hide collections menu on the navbar
Hide the App Dock Icon: Hide the App Dock Icon
History Item Preview Max Lines: History Item Preview Max Lines
'How to set hotkeys:': 'How to set hotkeys:'
Keep Items on Clear: Keep Items on Clear
Keep Pinned Items: Keep Pinned Items
Keep Starred Items: Keep Starred Items
? Keep the main application window hidden when the app restarts. You can reopen it using the menu bar or taskbar menu, or using global hotkeys.
: Keep the main application window hidden when the app restarts. You can reopen it using the menu bar or taskbar menu, or using global hotkeys.
Left-click toggles app visibility: Left-click toggles app visibility
Left-clicking the tray icon shows or hides the main application window: Left-clicking the tray icon shows or hides the main application window
No keys set: No keys set
'Note: At least one panel must remain visible in main window.': 'Note: At least one panel must remain visible in main window.'
Panel Visibility: Panel Visibility
PasteBar Quick Paste: PasteBar Quick Paste
Preserve pinned items when clearing history: Preserve pinned items when clearing history
Preserve starred items when clearing history: Preserve starred items when clearing history
Press Backspace/Delete to clear the hotkey: Press Backspace/Delete to clear the hotkey
Press Enter to confirm or Escape to cancel: Press Enter to confirm or Escape to cancel
Press keys: Press keys
Press your desired key combination (e.g., Ctrl+Shift+V): Press your desired key combination (e.g., Ctrl+Shift+V)
Press your key combination...: Press your key combination...
Prevents the context menu from appearing when left-clicking the tray icon: Prevents the context menu from appearing when left-clicking the tray icon
Preview Max Lines: Preview Max Lines
Quick Paste Window: Quick Paste Window
Quick Paste Window Options: Quick Paste Window Options
Recording...: Recording...
? Remove PasteBar app icon from the macOS Dock while keeping the app running in the background. The app remains accessible via the menu bar icon. Requires an app restart to take effect.
: Remove PasteBar app icon from the macOS Dock while keeping the app running in the background. The app remains accessible via the menu bar icon. Requires an app restart to take effect.
Set: Set
Set system OS hotkeys to show/hide the main app window and quick paste window. Supports up to 3-key combinations.: Set system OS hotkeys to show/hide the main app window and quick paste window. Supports up to 3-key combinations.
Set the maximum number of lines to display in the preview of a history item: Set the maximum number of lines to display in the preview of a history item
Show Boards and Clips Panel Only: Show Boards and Clips Panel Only
Show Both Panels: Show Both Panels
Show History Panel Only: Show History Panel Only
Show Navbar Items Hover: Show Navbar Items Hover
Show Note Icons on Clips: Show Note Icons on Clips
Show Simplified Layout: Show Simplified Layout
Show collections menu on the navbar: Show collections menu on the navbar
Show navbar elements on hover only: Show navbar elements on hover only
Show/Hide Main App Window: Show/Hide Main App Window
Show/Hide Quick Paste Window: Show/Hide Quick Paste Window
Simplified Panel Layout: Simplified Panel Layout
Single Click Copy/Paste: Single Click Copy/Paste
Single Click Copy/Paste action: Single Click Copy/Paste action
Set keyboard focus with a single click. Disables single-click copy/paste if set.: Set keyboard focus with a single click. Disables single-click copy/paste if set.
Single-Click Keyboard Focus: Single-Click Keyboard Focus
This sets the default icon type for new clips with notes. You can customize individual clips via the context menu.: This sets the default icon type for new clips with notes. You can customize individual clips via the context menu.
Tray Icon Behavior on Windows: Tray Icon Behavior on Windows
? When enabled, clicking menu items will only copy content to clipboard instead of auto-pasting. This gives you more control over when and where content is pasted.
: When enabled, clicking menu items will only copy content to clipboard instead of auto-pasting. This gives you more control over when and where content is pasted.
? When enabled, clicking or pressing Enter on items in Quick Paste window will only copy them to clipboard without automatically pasting.
: When enabled, clicking or pressing Enter on items in Quick Paste window will only copy them to clipboard without automatically pasting.
? When enabled, single click will copy/paste items in Quick Paste window. If global single click is also enabled, both settings work together.
: When enabled, single click will copy/paste items in Quick Paste window. If global single click is also enabled, both settings work together.
When enabled, the Quick Paste window will automatically close after copying or pasting an item.: When enabled, the Quick Paste window will automatically close after copying or pasting an item.
