App restart required: Требуется перезапуск
Application Starts with Main Window Hidden: Приложение запускается со скрытым главным окном
Change: Изменить
Copy only from menu items: Копировать только из элементов меню
Display navbar items only when the mouse hovers over the navigation bar to minimize visible UI elements: Отображать элементы панели навигации только при наведении мыши для минимизации видимых элементов интерфейса
Global System OS Hotkeys: Глобальные системные горячие клавиши
Hide Collections Navbar: Скрыть панель коллекций
Hide collections menu dropdown on the navigation bar: Скрыть выпадающее меню коллекций на панели навигации
Hide collections menu on the navbar: Скрыть меню коллекций на панели навигации
Hide the App Dock Icon: Скрыть иконку приложения в Dock
Keep the main application window hidden when the app restarts. You can reopen it using the menu bar or taskbar menu, or using global hotkeys.: Держать главное окно приложения скрытым при перезапуске. Вы можете открыть его через меню в строке меню или панели задач, или используя глобальные горячие клавиши.
No keys set: Клавиши не установлены
Press keys: Нажмите клавиши
Remove PasteBar app icon from the macOS Dock while keeping the app running in the background. The app remains accessible via the menu bar icon. Requires an app restart to take effect.: Удалить иконку PasteBar из macOS Dock, оставляя приложение запущенным в фоне. Приложение остается доступным через иконку в строке меню. Требуется перезапуск приложения.
Set: Установить
Set system OS hotkeys to show/hide the main app window and quick paste window: Установить системные горячие клавиши для показа/скрытия главного окна и окна быстрой вставки. Поддерживает комбинации до 3 клавиш.
'How to set hotkeys:': 'Как установить горячие клавиши:'
Click Set/Change button to start recording: Нажмите кнопку Установить/Изменить для начала записи
Press your desired key combination (e.g., Ctrl+Shift+V): Нажмите желаемую комбинацию клавиш (например, Ctrl+Shift+V)
Press Enter to confirm or Escape to cancel: Нажмите Enter для подтверждения или Escape для отмены
Press Backspace/Delete to clear the hotkey: Нажмите Backspace/Delete для очистки горячей клавиши
Press your key combination...: Нажмите вашу комбинацию клавиш...
Recording...: Запись...
Show Navbar Items Hover: Показывать элементы панели при наведении
Show collections menu on the navbar: Показывать меню коллекций на панели навигации
Show navbar elements on hover only: Показывать элементы панели только при наведении
Show/Hide Main App Window: Показать/Скрыть главное окно
Show/Hide Quick Paste Window: Показать/Скрыть окно быстрой вставки
PasteBar Quick Paste: PasteBar Быстрая Вставка
Show Note Icons on Clips: Показывать иконку заметок на клипах
Display persistent icons on clips that have notes to improve visual organization and make notes easier to discover.: Отображать постоянные значки на клипах с заметками для улучшения визуальной организации и облегчения поиска заметок.
Default Note Icon Type: Тип иконки заметки по умолчанию
Boards, saved clips and menu items panel visible: Панель досок, сохранённых клипов и элементов меню видима
Both clipboard history and saved clips panels visible: Обе панели истории буфера и сохранённых клипов видимы
Clipboard history panel visible: Панель истории буфера видима
Control which panels are visible in the main window: Контроль того, какие панели видимы в главном окне
Enable simplified, less boxy layout for a cleaner and more streamlined interface design: Включить упрощённый, менее квадратный дизайн для более чистого и оптимизированного интерфейса
'Note: At least one panel must remain visible in main window.': 'Примечание: По крайней мере одна панель должна оставаться видимой в главном окне.'
Panel Visibility: Видимость панелей
Show Boards and Clips Panel Only: Показывать только панель досок и клипов
Show Both Panels: Показывать обе панели
Show History Panel Only: Показывать только панель истории
Show Simplified Layout: Показывать упрощённый интерфейс
Simplified Panel Layout: Упрощённый дизайн панелей
Enable single-click to copy/paste clipboard history items and saved clips instead of requiring double-click.: Включить копирование/вставку элементов истории буфера обмена и сохранённых клипов одним кликом вместо двойного клика.
Single Click Copy/Paste action: Действие копирования/вставки одним кликом
Single Click Copy/Paste: Копирование/вставка одним кликом
Set keyboard focus with a single click. Disables single-click copy/paste if set.: Установить фокус клавиатуры одним кликом. Отключает копирование/вставку одним кликом, если установлено.
Single-Click Keyboard Focus: Фокус клавиатуры одним кликом
Quick Paste Window: Окно быстрой вставки
Quick Paste Window Options: Параметры окна быстрой вставки
Configure the behavior of the Quick Paste window when selecting items: Настроить поведение окна быстрой вставки при выборе элементов
Configure how the system tray icon responds to mouse clicks: Настроить, как иконка системного трея реагирует на клики мыши
Disable left-click context menu: Отключить контекстное меню левого клика
Double-click toggles app visibility: Двойной клик переключает видимость приложения
Double-clicking the tray icon shows or hides the main application window: Двойной клик по иконке трея показывает или скрывает главное окно приложения
Enabling either left-click option will disable the context menu to ensure proper functionality.: Включение любой из опций левого клика отключит контекстное меню для обеспечения правильной функциональности.
Left-click toggles app visibility: Левый клик переключает видимость приложения
Left-clicking the tray icon shows or hides the main application window: Левый клик по иконке трея показывает или скрывает главное окно приложения
Prevents the context menu from appearing when left-clicking the tray icon: Предотвращает появление контекстного меню при левом клике по иконке трея
Tray Icon Behavior on Windows: Поведение иконки трея в Windows
This sets the default icon type for new clips with notes. You can customize individual clips via the context menu.: Это устанавливает тип иконки по умолчанию для новых клипов с заметками. Вы можете настроить отдельные клипы через контекстное меню.
? When enabled, clicking menu items will only copy content to clipboard instead of auto-pasting. This gives you more control over when and where content is pasted.
: Когда включено, нажатие на элементы меню будет только копировать содержимое в буфер обмена вместо автоматической вставки. Это дает вам больше контроля над тем, когда и где вставляется содержимое.
? When enabled, clicking or pressing Enter on items in Quick Paste window will only copy them to clipboard without automatically pasting.
: Когда включено, нажатие или нажатие Enter на элементы в окне быстрой вставки будет только копировать их в буфер обмена без автоматической вставки.
? When enabled, single click will copy/paste items in Quick Paste window. If global single click is also enabled, both settings work together.
: Когда включено, одним кликом будут копироваться/вставляться элементы в окне быстрой вставки. Если глобальный одиночный клик также включен, обе настройки работают вместе.
Configure which items to preserve when clearing clipboard history (both manual and auto-clear operations).: Настройте, какие элементы сохранять при очистке истории буфера обмена (как вручную, так и автоматически).
Keep Items on Clear: Сохранять элементы при очистке
Keep Pinned Items: Сохранять закрепленные элементы
Keep Starred Items: Сохранять избранные элементы
Preserve pinned items when clearing history: Сохранять закрепленные элементы при очистке истории
Preserve starred items when clearing history: Сохранять избранные элементы при очистке истории
History Item Preview Max Lines: Количество строк предварительного просмотра элементов истории
Set the maximum number of lines to display in the preview of a history item: Установить максимальное количество строк для отображения в предварительном просмотре элемента истории
Preview Max Lines: Максимум строк просмотра
